excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://blessthinker.github.io
title: Brighter Bulb
tagline: A speech of life
description: Want to be a outspoken thinker, have a midblown idea.
paginate: 5